import type { Locale } from './i18n/locale';
import type { TaskUnit } from './presence';

const fr = {
  today: 'Aujourd’hui', teamOverview: 'Votre équipe, en un regard.',
  employees: 'Employés', confirmed: 'Présence confirmée', review: 'À vérifier', hours: 'Heures déclarées',
  hoursHint: 'Durée des journées déclarées. Une vérification ponctuelle ne mesure pas le temps réellement travaillé.',
  productivity: 'Productivité', productivityHint: 'Les réalisations déclarées aujourd’hui, chantier par chantier.', declarations: 'Déclarations', contributors: 'Contributeurs',
  headcount: 'Employés dans l’entreprise', activeSuffix: 'actifs', onSiteToday: 'ont confirmé leur présence aujourd’hui', perTask: 'employé(s)',
  liveTitle: 'Carte', liveHint: 'Uniquement les employés dont vous avez activé la localisation en direct, pendant leur journée déclarée.',
  noLive: 'Personne ne partage sa position actuellement.', noLiveHint: 'Activez la localisation en direct sur la fiche d’un employé, puis attendez qu’il accepte et démarre sa journée.',
  liveNoticeTitle: 'Partage de position en direct', liveNoticeIntro: 'Votre chef a activé le suivi en direct pour votre compte. Il ne démarrera qu’avec votre accord.',
  liveNoticeCollection: 'Pendant vos journées de travail déclarées uniquement, votre position est transmise environ toutes les 2 minutes, y compris lorsque l’application est en arrière-plan. Le partage s’arrête dès que vous terminez votre journée.',
  liveNoticePrivacy: 'Seule votre position la plus récente est conservée : aucun historique de déplacement n’est constitué. Elle disparaît de l’écran de votre chef après 15 minutes sans mise à jour, et est effacée à la fin de la journée.',
  liveNoticeRights: 'Vous pouvez retirer votre accord à tout moment : le partage s’arrête immédiatement et votre dernière position est effacée. Votre chef ayant activé le suivi pour votre poste, vous ne pourrez pas déclarer de journée tant que vous n’aurez pas répondu. Vous gardez l’accès à votre compte et pouvez vous déconnecter à tout moment.',
  liveAgree: 'J’accepte de partager ma position en direct pendant mes journées déclarées.', liveAccept: 'Activer le partage', liveWithdraw: 'Retirer mon accord',
  foregroundOnly: 'Partage limité à l’app ouverte',
  myPosition: 'Ma position', sharedWithChef: 'Partagée avec votre chef', notSharedYet: 'Position pas encore envoyée.', refreshPosition: 'Actualiser ma position', lastShared: 'Dernier envoi',
  gateTitle: 'Avant de commencer', gateHint: 'Votre accord est nécessaire pour utiliser l’application. Vous pouvez vous déconnecter si vous préférez ne pas répondre maintenant.', signOut: 'Se déconnecter',
  liveOn: 'Partage en direct actif', liveOff: 'Partage en direct en attente de votre accord', livePermissionDenied: 'Autorisez la position « Toujours » pour partager en direct pendant votre journée.',
  noTasks: 'Aucune tâche déclarée pour le moment.', consistency: 'Points de cohérence', consistencyHint: 'Même tâche, même chantier et même quantité sur les 3 dernières journées travaillées. À discuter avec l’équipe ; aucun blocage.',
  dayTitle: 'Ma journée', site: 'Chantier', chooseSite: 'Choisir un chantier',
  awaitingHere: 'Tâches attendues', noSites: 'Votre chef doit d’abord ajouter un chantier.',
  hourUnit: 'h', minuteUnit: 'min', elapsedLabel: 'Temps écoulé', workedLabel: 'Durée travaillée',
  showPassword: 'Afficher le mot de passe', hidePassword: 'Masquer le mot de passe',
  backToToday: 'Revenir à aujourd’hui',
  history30: 'Journées précédentes', historyEmpty: 'Aucune journée enregistrée.', pickDay: 'Voir les journées précédentes', dayOngoing: 'En cours',
  liveStats: 'Aujourd’hui', noDayToday: 'Aucune journée déclarée aujourd’hui.', checksToday: 'Vérifications réalisées', missedToday: 'Demandes manquées',
  removeSite: 'Supprimer le chantier', removeSiteConfirm: 'Retirer ce chantier de la liste ? S’il a déjà été travaillé, il est archivé et son historique reste consultable.', removeSiteHint: 'Appui long sur un chantier pour le retirer',
  cancelDay: 'Annuler cette journée', cancelDayConfirm: 'Supprimer cette journée ? Elle disparaîtra sans laisser de trace. À utiliser si vous vous êtes trompé de chantier.', cancelDayHint: 'Appui long pour annuler cette journée',
  onSite: 'Sur le chantier', offSite: 'Hors zone', offSiteAt: (m: number) => `Hors zone · à ${m >= 1000 ? (m / 1000).toFixed(1) + ' km' : m + ' m'} du chantier`, zoneUnknown: 'Chantier non localisé, distance inconnue', zoneHint: 'Zone de 5 km autour du chantier. Le temps sans relevé n’est compté nulle part : l’application ne relève votre position que lorsqu’elle est ouverte ou que le téléphone bouge.',
  zonePartly: (d: string) => `${d} sans relevé de position.`,
  zoneNothing: 'Aucun relevé de position pour l’instant : impossible de dire si vous êtes sur le chantier.', duration: 'Durée prévue', startsLabel: 'Début', endsLabel: 'Fin prévue', start: 'Commencer ma journée', finish: 'Terminer ma journée', finishConfirm: 'Terminer maintenant ? Les demandes futures seront annulées. Pensez à enregistrer vos tâches avant de terminer.',
  cancel: 'Annuler', save: 'Enregistrer', loading: 'Chargement…', retry: 'Réessayer', refresh: 'Actualiser', dayDoneHint: 'Journée terminée. Vos déclarations et vérifications sont enregistrées.',
  proofsTitle: 'Mes vérifications de présence',
  presence: 'Vérification de présence', requestReady: 'Une vérification vous attend', deadline: 'Répondre avant', capture: 'Prendre la photo et vérifier ma présence',
  captureHint: 'Prenez une photo du chantier, sans visage ni document personnel. Votre GPS sera relevé une seule fois, juste après la photo.',
  waiting: 'Aucune vérification à faire maintenant.', waitingHint: 'Vous recevrez 2 ou 3 demandes à des moments variables pendant votre journée. Aucun GPS n’est collecté entre les demandes.',
  verified: 'Vérification enregistrée', missed: 'Demande à vérifier avec votre chef', checksDone: 'vérification(s) réalisée(s)',
  noticeTitle: 'Votre présence, à des moments précis', noticeIntro: 'Avant d’activer les vérifications, prenez connaissance de leur fonctionnement.',
  noticeCollection: '2 ou 3 fois pendant votre journée déclarée, une notification vous invitera à prendre une photo du chantier et à transmettre votre position GPS actuelle avec sa précision, l’heure et le chantier déclaré. Vous avez 30 minutes pour répondre.',
  noticePrivacy: 'Aucun suivi continu ni accès à votre position en arrière-plan. La caméra et le GPS ne s’activent qu’après votre appui. Évitez les visages et les informations personnelles dans la photo. Aucune reconnaissance faciale.',
  noticeAccess: 'Les preuves sont accessibles à vous et aux chefs de votre entreprise pour vérifier la présence sur le chantier. Les photos et coordonnées sont conservées au maximum 30 jours. Les journées et tâches déclarées restent dans l’historique de l’entreprise.',
  noticeRights: 'Votre entreprise est responsable de cette utilisation. Contactez votre chef pour obtenir ses coordonnées, exercer vos droits d’accès, de rectification ou d’opposition, ou signaler une difficulté. Vous pouvez retirer votre accord dans cet écran ; les nouvelles demandes cessent alors.',
  noticeChoice: 'Tant que vous n’avez pas accepté, vous ne pouvez pas déclarer de journée ni de tâches : ces fonctions reposent sur ces vérifications. Vous gardez l’accès à votre compte et pouvez vous déconnecter à tout moment. Une vérification non réalisée n’est pas une preuve d’absence. Les démarches et la base légale applicables doivent être précisées par votre employeur.',
  agreeLabel: 'J’ai lu ces informations et j’accepte les vérifications ponctuelles avec photo et GPS.', accept: 'Activer les vérifications', later: 'Plus tard', withdraw: 'Retirer mon accord', withdrawConfirm: 'Retirer votre accord terminera la journée en cours et arrêtera les nouvelles demandes.', info: 'Information et accord',
  tasksDone: 'Tâches réalisées',
  taskTitle: 'Mes tâches', taskHint: 'Choisissez une tâche et indiquez la quantité totale réalisée aujourd’hui. Une nouvelle saisie remplace la quantité précédente.',
  category: 'Métier', task: 'Tâche', chooseTask: 'Choisir une tâche', quantity: 'Quantité réalisée', unit: 'unité(s)', metres: 'mètres', taskSaved: 'Déclaration enregistrée', startForTasks: 'Commencez votre journée pour déclarer vos tâches.',
  unitLong: { unit: 'unité(s)', m: 'mètres', m2: 'mètres carrés', m3: 'mètres cubes', kg: 'kilogrammes' }, unitShort: { unit: 'u', m: 'm', m2: 'm²', m3: 'm³', kg: 'kg' },
  whole: 'Nombre entier', decimal: 'Décimales', useKeyboard: 'Saisir au clavier', useWheel: 'Utiliser la molette',
  extraTitle: 'Autre chose faite sur le chantier',
  extraHint: 'Ce qui n’est ni dans le devis ni dans la liste : un imprévu, une reprise, une attente.',
  extraPlaceholder: 'Ex. : coffrage refait, le premier coulage avait raté.',
  extraAdd: 'Ajouter',
  extraRemove: 'Supprimer',
  noteTitle: 'Message à l’équipe du chantier',
  noteSend: 'Envoyer',
  noteDelete: 'Supprimer', noteDeleteConfirm: 'Retirer ce message ? Les employés ne le verront plus.',
  noteNone: 'Aucune consigne pour le moment.',
  noteFrom: (who: string) => `De ${who}`,
  sitesTitle: 'Chantiers', addSite: 'Ajouter un chantier', siteName: 'Nom du chantier', siteAddress: 'Adresse du chantier',
  siteAddressSearch: 'Chercher une adresse',
  siteNameExample: 'Ex. Résidence Les Oliviers',
  siteAddressSearchFailed: 'Recherche d’adresse indisponible. Placez le repère à la main.',
  siteAddressHint: 'Cherchez l’adresse, ou déplacez la carte pour placer le repère sur un chantier qui n’en a pas.',
  pinLocating: 'Recherche de l’adresse…', pinNoAddress: 'Aucune adresse à cet endroit. Déplacez le repère.', pinUseMyLocation: 'Revenir à ma position',
  pinPermission: 'Position refusée : la carte démarre sur le Maroc, déplacez le repère jusqu’au chantier.',
  addressUnknown: 'Adresse introuvable dans Plans. Précisez la rue et la ville, puis réessayez.', addressNeeded: 'L’adresse est obligatoire.',
  geocodeUnavailable: 'Utilisez l’application mobile pour ajouter un chantier : la validation d’adresse n’est pas disponible sur le web.',
  siteNoCoords: 'Chantier sans adresse localisée, absent de la carte.', siteLegend: 'Chantiers',
  noSitesLocated: 'Aucun chantier localisé. Ajoutez-en un depuis l’onglet Chantiers.',
  notLocatable: 'Position non partagée', locateOnMap: 'Voir sur la carte',
  lastSeen: 'Vu pour la dernière fois', neverSeen: 'Jamais localisé sur ce chantier',
  justNow: 'à l’instant', minutesAgo: (n: number) => `il y a ${n} min`, hoursAgo: (n: number) => `il y a ${n} h`, stalePosition: 'Position non rafraîchie : l’employé n’a pas bougé ou son app est fermée.',
  siteTeam: 'Employés du chantier', siteTeamHint: 'Les employés qui ont déclaré des journées sur ce chantier.', siteTeamEmpty: 'Aucun employé n’a encore déclaré de journée ici.',
  presentToday: 'Sur le chantier aujourd’hui', lastDay: 'Dernière journée', daysWorked: 'journée(s)', suspended: 'Compte suspendu', liveOnBadge: 'Direct',
  history: 'Vérifications', historyHint: 'Des preuves ponctuelles, avec l’heure et le chantier déclaré. Aucune position en direct.', noChecks: 'Aucune vérification enregistrée.', viewProof: 'Voir la preuve', close: 'Fermer', accuracy: 'Précision GPS',
  pushUnavailable: 'Notifications indisponibles sur cet appareil. Gardez l’écran Aujourd’hui ouvert et actualisez-le pour voir les demandes.',
  nativeOnly: 'Utilisez l’application mobile pour prendre une photo sur place et relever votre position.',
  cameraDenied: 'Autorisez la caméra pour prendre la photo du chantier.', locationDenied: 'Autorisez votre position pendant cette vérification.',
  failed: 'Impossible de charger les données. Réessayez.', invalidQuantity: 'Saisissez une quantité positive valide (un nombre entier pour les unités).',
  proofFailed: 'La vérification n’a pas été enregistrée. Reprenez une photo et réessayez pendant la fenêtre de réponse.',
  inactive: 'Ce compte est suspendu. Contactez votre chef.',
  quoteTooLarge: 'Ce fichier dépasse 20 Mo. Photographiez le devis page par page ou réduisez le PDF.',
  quoteUploadFailed: 'Le devis n’a pas été envoyé. Vérifiez votre connexion et réessayez.',
};
const en: typeof fr = {
  today: 'Today', teamOverview: 'Your team at a glance.',
  employees: 'Employees', confirmed: 'Presence confirmed', review: 'To review', hours: 'Declared hours',
  hoursHint: 'Duration of declared work days. Occasional checks do not measure actual time worked.',
  productivity: 'Productivity', productivityHint: 'Today’s declared work, site by site.', declarations: 'Declarations', contributors: 'Contributors',
  headcount: 'Employees in the company', activeSuffix: 'active', onSiteToday: 'confirmed their presence today', perTask: 'employee(s)',
  liveTitle: 'Map', liveHint: 'Only employees you enabled live location for, during their declared work day.',
  noLive: 'Nobody is sharing their location right now.', noLiveHint: 'Enable live location on an employee, then wait for them to agree and start their day.',
  liveNoticeTitle: 'Live location sharing', liveNoticeIntro: 'Your chef enabled live tracking for your account. It only starts once you agree.',
  liveNoticeCollection: 'During your declared work days only, your position is sent roughly every 2 minutes, including while the app is in the background. Sharing stops as soon as you finish your day.',
  liveNoticePrivacy: 'Only your most recent position is kept: no movement history is built. It disappears from your chef’s screen after 15 minutes without an update, and is erased when the day ends.',
  liveNoticeRights: 'You can withdraw at any time: sharing stops immediately and your last position is erased. Because your chef enabled tracking for your role, you cannot declare a work day until you answer. You keep access to your account and can sign out at any time.',
  liveAgree: 'I agree to share my live location during my declared work days.', liveAccept: 'Enable sharing', liveWithdraw: 'Withdraw agreement',
  foregroundOnly: 'Shared while app is open',
  myPosition: 'My position', sharedWithChef: 'Shared with your chef', notSharedYet: 'Position not sent yet.', refreshPosition: 'Refresh my position', lastShared: 'Last sent',
  gateTitle: 'Before you start', gateHint: 'Your agreement is required to use the app. You can sign out if you would rather not answer now.', signOut: 'Sign out',
  liveOn: 'Live sharing active', liveOff: 'Live sharing waiting for your agreement', livePermissionDenied: 'Allow "Always" location to share live during your day.',
  noTasks: 'No tasks declared yet.', consistency: 'Consistency notes', consistencyHint: 'Same task, site and quantity on the last 3 work days. Discuss with the team; this never blocks a declaration.',
  dayTitle: 'My day', site: 'Site', chooseSite: 'Choose a site',
  awaitingHere: 'Tasks expected', noSites: 'Your chef needs to add a site first.',
  hourUnit: 'h', minuteUnit: 'min', elapsedLabel: 'Elapsed', workedLabel: 'Time worked',
  showPassword: 'Show password', hidePassword: 'Hide password',
  backToToday: 'Back to today',
  history30: 'Previous days', historyEmpty: 'No work day recorded yet.', pickDay: 'See previous days', dayOngoing: 'Ongoing',
  liveStats: 'Today', noDayToday: 'No work day declared today.', checksToday: 'Checks completed', missedToday: 'Missed requests',
  removeSite: 'Delete site', removeSiteConfirm: 'Remove this site from the list? If it has been worked on, it is archived and its history stays readable.', removeSiteHint: 'Long-press a site to remove it',
  cancelDay: 'Cancel this day', cancelDayConfirm: 'Delete this work day? It will disappear without a trace. Use this if you picked the wrong site.', cancelDayHint: 'Long-press to cancel this day',
  onSite: 'On site', offSite: 'Off site', offSiteAt: (m: number) => `Off site · ${m >= 1000 ? (m / 1000).toFixed(1) + ' km' : m + ' m'} from the site`, zoneUnknown: 'Site not located, distance unknown', zoneHint: 'A 5 km zone around the site. Time without a reading is counted nowhere: the app only takes a position while it is open or the phone is moving.',
  zonePartly: (d: string) => `${d} with no position reading.`,
  zoneNothing: 'No position reading yet, so there is no saying whether you are on site.', duration: 'Planned duration', startsLabel: 'Start', endsLabel: 'Expected end', start: 'Start my day', finish: 'Finish my day', finishConfirm: 'Finish now? Future requests will be cancelled. Remember to save your tasks first.',
  cancel: 'Cancel', save: 'Save', loading: 'Loading…', retry: 'Retry', refresh: 'Refresh', dayDoneHint: 'Day finished. Your declarations and checks are saved.',
  proofsTitle: 'My presence checks',
  presence: 'Presence check', requestReady: 'A check is waiting for you', deadline: 'Respond before', capture: 'Take a photo and confirm my presence',
  captureHint: 'Photograph the site without faces or personal documents. Your GPS position will be captured once, just after the photo.',
  waiting: 'No check to complete right now.', waitingHint: 'You will receive 2 or 3 requests at varying times during your day. No GPS is collected between requests.',
  verified: 'Check saved', missed: 'Review this request with your chef', checksDone: 'check(s) completed',
  noticeTitle: 'Your presence, at specific moments', noticeIntro: 'Please read how checks work before enabling them.',
  noticeCollection: '2 or 3 times during your declared work day, a notification will ask for a site photo and your current GPS position, its accuracy, the time and the declared site. You have 30 minutes to respond.',
  noticePrivacy: 'No continuous tracking or background location access. The camera and GPS only activate after you tap. Avoid faces and personal information in the photo. No facial recognition.',
  noticeAccess: 'Proofs are available to you and your company’s chefs to check site presence. Photos and coordinates are retained for at most 30 days. Declared days and tasks remain in the company history.',
  noticeRights: 'Your company is responsible for this use. Contact your chef for its contact details, to exercise access, correction or objection rights, or to report a difficulty. You can withdraw agreement here to stop new requests.',
  noticeChoice: 'Until you accept, you cannot declare a work day or tasks: those features rest on these checks. You keep access to your account and can sign out at any time. A missed check is not proof of absence. Your employer must specify the applicable legal basis and requirements.',
  agreeLabel: 'I have read this information and agree to occasional checks with a photo and GPS.', accept: 'Enable checks', later: 'Later', withdraw: 'Withdraw agreement', withdrawConfirm: 'Withdrawing agreement will finish the current day and stop new requests.', info: 'Information and agreement',
  tasksDone: 'Completed tasks',
  taskTitle: 'My tasks', taskHint: 'Choose a task and enter the total quantity completed today. Saving again replaces the previous quantity.',
  category: 'Trade', task: 'Task', chooseTask: 'Choose a task', quantity: 'Quantity completed', unit: 'unit(s)', metres: 'metres', taskSaved: 'Declaration saved', startForTasks: 'Start your day to declare tasks.',
  unitLong: { unit: 'unit(s)', m: 'metres', m2: 'square metres', m3: 'cubic metres', kg: 'kilograms' }, unitShort: { unit: 'u', m: 'm', m2: 'm²', m3: 'm³', kg: 'kg' },
  whole: 'Whole number', decimal: 'Decimals', useKeyboard: 'Type on keyboard', useWheel: 'Use the wheel',
  extraTitle: 'Something else done on site',
  extraHint: 'What is in neither the devis nor the list: something unforeseen, a redo, a wait.',
  extraPlaceholder: 'E.g. shuttering rebuilt, the first pour went wrong.',
  extraAdd: 'Add',
  extraRemove: 'Delete',
  noteTitle: 'Message to the site crew',
  noteSend: 'Send',
  noteDelete: 'Delete', noteDeleteConfirm: 'Remove this message? The crew will no longer see it.',
  noteNone: 'Nothing posted yet.',
  noteFrom: (who: string): string => `From ${who}`,
  sitesTitle: 'Sites', addSite: 'Add a site', siteName: 'Site name', siteAddress: 'Site address',
  siteAddressSearch: 'Search for an address',
  siteNameExample: 'e.g. Les Oliviers Residence',
  siteAddressSearchFailed: 'Address search is unavailable. Place the pin by hand.',
  siteAddressHint: 'Search for the address, or move the map to place the pin on a site that has none.',
  pinLocating: 'Looking up the address…', pinNoAddress: 'No address here. Move the pin.', pinUseMyLocation: 'Back to my location',
  pinPermission: 'Location denied: the map starts on Morocco, move the pin to the site.',
  addressUnknown: 'Maps could not find that address. Add the street and city, then try again.', addressNeeded: 'The address is required.',
  geocodeUnavailable: 'Use the mobile app to add a site: address validation is unavailable on web.',
  siteNoCoords: 'Site without a located address, missing from the map.', siteLegend: 'Sites',
  noSitesLocated: 'No located site yet. Add one from the Sites tab.',
  notLocatable: 'Position not shared', locateOnMap: 'Show on the map',
  lastSeen: 'Last time seen', neverSeen: 'Never located on this site',
  justNow: 'just now', minutesAgo: (n: number) => `${n} min ago`, hoursAgo: (n: number) => `${n} h ago`, stalePosition: 'Position not refreshed: the employee has not moved, or their app is closed.',
  siteTeam: 'Site team', siteTeamHint: 'Employees who have declared work days on this site.', siteTeamEmpty: 'No employee has declared a day here yet.',
  presentToday: 'On site today', lastDay: 'Last work day', daysWorked: 'day(s)', suspended: 'Account suspended', liveOnBadge: 'Live',
  history: 'Checks', historyHint: 'Occasional proofs with time and declared site. No live locations.', noChecks: 'No checks recorded yet.', viewProof: 'View proof', close: 'Close', accuracy: 'GPS accuracy',
  pushUnavailable: 'Notifications are unavailable on this device. Keep Today open and refresh to see requests.',
  nativeOnly: 'Use the mobile app to take an on-site photo and capture your position.',
  cameraDenied: 'Allow camera access to take a site photo.', locationDenied: 'Allow location access for this check.',
  failed: 'Unable to load data. Please retry.', invalidQuantity: 'Enter a valid positive quantity (a whole number for units).',
  proofFailed: 'The check was not saved. Take a new photo and retry within the response window.',
  inactive: 'This account is suspended. Contact your chef.',
  quoteTooLarge: 'This file is over 20 MB. Photograph the quote page by page, or shrink the PDF.',
  quoteUploadFailed: 'The quote was not uploaded. Check your connection and try again.',
};
export function workCopy(locale: Locale) { return locale === 'en' ? en : fr; }

/** A position older than this is shown as dated rather than treated as current. */
export const STALE_AFTER_MS = 15 * 60 * 1000;

/** "3 h 24 min" once past an hour, "24 min" below it. */
export function formatElapsed(milliseconds: number, copy: typeof fr) {
  const minutes = Math.max(0, Math.floor(milliseconds / 60_000));
  const hours = Math.floor(minutes / 60);
  const rest = minutes % 60;
  return hours ? `${hours} ${copy.hourUnit} ${rest} ${copy.minuteUnit}` : `${rest} ${copy.minuteUnit}`;
}

export function positionAge(recordedAt: string, copy: typeof fr, now = Date.now()) {
  const elapsed = Math.max(0, now - Date.parse(recordedAt));
  const minutes = Math.floor(elapsed / 60_000);
  if (minutes < 1) return copy.justNow;
  if (minutes < 60) return copy.minutesAgo(minutes);
  return copy.hoursAgo(Math.floor(minutes / 60));
}

/** Only whole units can be declared for countable tasks; every measured unit accepts decimals. */
export function isWholeUnit(unit: TaskUnit) { return unit === 'unit'; }
export function unitLong(unit: TaskUnit, copy: typeof fr) { return copy.unitLong[unit] ?? unit; }
export function unitShort(unit: TaskUnit, copy: typeof fr) { return copy.unitShort[unit] ?? unit; }
