import type { Locale } from './i18n/locale';
import type { TaskUnit } from './presence';

const fr = {
  today: 'Aujourd’hui', teamOverview: 'Votre équipe, en un regard.', teamSubtitle: 'Présence ponctuelle et travail déclaré, sans suivi continu.',
  employees: 'Employés', confirmed: 'Présence confirmée', review: 'À vérifier', hours: 'Heures déclarées',
  hoursHint: 'Durée des journées déclarées. Une vérification ponctuelle ne mesure pas le temps réellement travaillé.',
  productivity: 'Productivité', productivityHint: 'Les réalisations déclarées aujourd’hui, tâche par tâche.', declarations: 'Déclarations', contributors: 'Contributeurs',
  headcount: 'Employés dans l’entreprise', activeSuffix: 'actifs', onSiteToday: 'ont confirmé leur présence aujourd’hui', perTask: 'employé(s)',
  liveTitle: 'Équipe en direct', liveHint: 'Uniquement les employés dont vous avez activé la localisation en direct, pendant leur journée déclarée.',
  noLive: 'Personne ne partage sa position actuellement.', noLiveHint: 'Activez la localisation en direct sur la fiche d’un employé, puis attendez qu’il accepte et démarre sa journée.',
  liveNoticeTitle: 'Partage de position en direct', liveNoticeIntro: 'Votre chef a activé le suivi en direct pour votre compte. Il ne démarrera qu’avec votre accord.',
  liveNoticeCollection: 'Pendant vos journées de travail déclarées uniquement, votre position est transmise environ toutes les 2 minutes, y compris lorsque l’application est en arrière-plan. Le partage s’arrête dès que vous terminez votre journée.',
  liveNoticePrivacy: 'Seule votre position la plus récente est conservée : aucun historique de déplacement n’est constitué. Elle disparaît de l’écran de votre chef après 15 minutes sans mise à jour, et est effacée à la fin de la journée.',
  liveNoticeRights: 'Vous pouvez retirer votre accord à tout moment dans cet écran : le partage s’arrête immédiatement et votre dernière position est effacée. Le refus n’empêche pas l’accès à votre compte ni la déclaration de vos tâches.',
  liveAgree: 'J’accepte de partager ma position en direct pendant mes journées déclarées.', liveAccept: 'Activer le partage', liveWithdraw: 'Retirer mon accord',
  liveOn: 'Partage en direct actif', liveOff: 'Partage en direct en attente de votre accord', livePermissionDenied: 'Autorisez la position « Toujours » pour partager en direct pendant votre journée.',
  noTasks: 'Aucune tâche déclarée pour le moment.', consistency: 'Points de cohérence', consistencyHint: 'Même tâche, même chantier et même quantité sur les 3 dernières journées travaillées. À discuter avec l’équipe ; aucun blocage.',
  dayTitle: 'Ma journée', daySubtitle: 'Un chantier. Des tâches. Quelques vérifications ponctuelles.', site: 'Chantier', chooseSite: 'Choisir un chantier', noSites: 'Votre chef doit d’abord ajouter un chantier.',
  duration: 'Durée prévue', start: 'Commencer ma journée', finish: 'Terminer ma journée', finishConfirm: 'Terminer maintenant ? Les demandes futures seront annulées. Pensez à enregistrer vos tâches avant de terminer.',
  cancel: 'Annuler', save: 'Enregistrer', loading: 'Chargement…', retry: 'Réessayer', refresh: 'Actualiser', dayDone: 'Journée terminée', dayDoneHint: 'Vos déclarations et vérifications sont enregistrées.',
  presence: 'Vérification de présence', requestReady: 'Une vérification vous attend', deadline: 'Répondre avant', capture: 'Prendre la photo et vérifier ma présence',
  captureHint: 'Prenez une photo du chantier, sans visage ni document personnel. Votre GPS sera relevé une seule fois, juste après la photo.',
  waiting: 'Aucune vérification à faire maintenant.', waitingHint: 'Vous recevrez 2 ou 3 demandes à des moments variables pendant votre journée. Aucun GPS n’est collecté entre les demandes.',
  verified: 'Vérification enregistrée', missed: 'Demande à vérifier avec votre chef', checksDone: 'vérification(s) réalisée(s)',
  noticeTitle: 'Votre présence, à des moments précis', noticeIntro: 'Avant d’activer les vérifications, prenez connaissance de leur fonctionnement.',
  noticeCollection: '2 ou 3 fois pendant votre journée déclarée, une notification vous invitera à prendre une photo du chantier et à transmettre votre position GPS actuelle avec sa précision, l’heure et le chantier déclaré. Vous avez 30 minutes pour répondre.',
  noticePrivacy: 'Aucun suivi continu ni accès à votre position en arrière-plan. La caméra et le GPS ne s’activent qu’après votre appui. Évitez les visages et les informations personnelles dans la photo. Aucune reconnaissance faciale.',
  noticeAccess: 'Les preuves sont accessibles à vous et aux chefs de votre entreprise pour vérifier la présence sur le chantier. Les photos et coordonnées sont conservées au maximum 30 jours. Les journées et tâches déclarées restent dans l’historique de l’entreprise.',
  noticeRights: 'Votre entreprise est responsable de cette utilisation. Contactez votre chef pour obtenir ses coordonnées, exercer vos droits d’accès, de rectification ou d’opposition, ou signaler une difficulté. Vous pouvez retirer votre accord dans cet écran ; les nouvelles demandes cessent alors.',
  noticeChoice: 'Refuser ou retirer votre accord n’empêche pas l’accès au compte. Une vérification non réalisée n’est pas une preuve d’absence. Les démarches et la base légale applicables doivent être précisées par votre employeur.',
  agreeLabel: 'J’ai lu ces informations et j’accepte les vérifications ponctuelles avec photo et GPS.', accept: 'Activer les vérifications', later: 'Plus tard', withdraw: 'Retirer mon accord', withdrawConfirm: 'Retirer votre accord terminera la journée en cours et arrêtera les nouvelles demandes.', info: 'Information et accord',
  taskTitle: 'Mes tâches', taskHint: 'Choisissez une tâche et indiquez la quantité totale réalisée aujourd’hui. Une nouvelle saisie remplace la quantité précédente.',
  category: 'Métier', task: 'Tâche', chooseTask: 'Choisir une tâche', quantity: 'Quantité réalisée', unit: 'unité(s)', metres: 'mètres', taskSaved: 'Déclaration enregistrée', startForTasks: 'Commencez votre journée pour déclarer vos tâches.',
  unitLong: { unit: 'unité(s)', m: 'mètres', m2: 'mètres carrés', m3: 'mètres cubes', kg: 'kilogrammes' }, unitShort: { unit: 'u', m: 'm', m2: 'm²', m3: 'm³', kg: 'kg' },
  whole: 'Nombre entier', decimal: 'Décimales', useKeyboard: 'Saisir au clavier', useWheel: 'Utiliser la molette',
  sitesTitle: 'Chantiers', sitesHint: 'Les chantiers que votre équipe peut déclarer.', addSite: 'Ajouter un chantier', siteName: 'Nom du chantier', siteAddress: 'Adresse (facultative)',
  history: 'Vérifications', historyHint: 'Des preuves ponctuelles, avec l’heure et le chantier déclaré. Aucune position en direct.', noChecks: 'Aucune vérification enregistrée.', viewProof: 'Voir la preuve', close: 'Fermer', accuracy: 'Précision GPS',
  pushUnavailable: 'Notifications indisponibles sur cet appareil. Gardez l’écran Aujourd’hui ouvert et actualisez-le pour voir les demandes.',
  nativeOnly: 'Utilisez l’application mobile pour prendre une photo sur place et relever votre position.',
  cameraDenied: 'Autorisez la caméra pour prendre la photo du chantier.', locationDenied: 'Autorisez votre position pendant cette vérification.',
  failed: 'Impossible de charger les données. Réessayez.', invalidQuantity: 'Saisissez une quantité positive valide (un nombre entier pour les unités).',
  proofFailed: 'La vérification n’a pas été enregistrée. Reprenez une photo et réessayez pendant la fenêtre de réponse.',
  inactive: 'Ce compte est suspendu. Contactez votre chef.',
};
const en: typeof fr = {
  today: 'Today', teamOverview: 'Your team at a glance.', teamSubtitle: 'Occasional presence checks and declared work, without continuous tracking.',
  employees: 'Employees', confirmed: 'Presence confirmed', review: 'To review', hours: 'Declared hours',
  hoursHint: 'Duration of declared work days. Occasional checks do not measure actual time worked.',
  productivity: 'Productivity', productivityHint: 'Today’s declared work, task by task.', declarations: 'Declarations', contributors: 'Contributors',
  headcount: 'Employees in the company', activeSuffix: 'active', onSiteToday: 'confirmed their presence today', perTask: 'employee(s)',
  liveTitle: 'Team live', liveHint: 'Only employees you enabled live location for, during their declared work day.',
  noLive: 'Nobody is sharing their location right now.', noLiveHint: 'Enable live location on an employee, then wait for them to agree and start their day.',
  liveNoticeTitle: 'Live location sharing', liveNoticeIntro: 'Your chef enabled live tracking for your account. It only starts once you agree.',
  liveNoticeCollection: 'During your declared work days only, your position is sent roughly every 2 minutes, including while the app is in the background. Sharing stops as soon as you finish your day.',
  liveNoticePrivacy: 'Only your most recent position is kept: no movement history is built. It disappears from your chef’s screen after 15 minutes without an update, and is erased when the day ends.',
  liveNoticeRights: 'You can withdraw at any time in this screen: sharing stops immediately and your last position is erased. Declining never prevents account access or task declarations.',
  liveAgree: 'I agree to share my live location during my declared work days.', liveAccept: 'Enable sharing', liveWithdraw: 'Withdraw agreement',
  liveOn: 'Live sharing active', liveOff: 'Live sharing waiting for your agreement', livePermissionDenied: 'Allow "Always" location to share live during your day.',
  noTasks: 'No tasks declared yet.', consistency: 'Consistency notes', consistencyHint: 'Same task, site and quantity on the last 3 work days. Discuss with the team; this never blocks a declaration.',
  dayTitle: 'My day', daySubtitle: 'One site. Your tasks. A few occasional checks.', site: 'Site', chooseSite: 'Choose a site', noSites: 'Your chef needs to add a site first.',
  duration: 'Planned duration', start: 'Start my day', finish: 'Finish my day', finishConfirm: 'Finish now? Future requests will be cancelled. Remember to save your tasks first.',
  cancel: 'Cancel', save: 'Save', loading: 'Loading…', retry: 'Retry', refresh: 'Refresh', dayDone: 'Day finished', dayDoneHint: 'Your declarations and checks are saved.',
  presence: 'Presence check', requestReady: 'A check is waiting for you', deadline: 'Respond before', capture: 'Take a photo and confirm my presence',
  captureHint: 'Photograph the site without faces or personal documents. Your GPS position will be captured once, just after the photo.',
  waiting: 'No check to complete right now.', waitingHint: 'You will receive 2 or 3 requests at varying times during your day. No GPS is collected between requests.',
  verified: 'Check saved', missed: 'Review this request with your chef', checksDone: 'check(s) completed',
  noticeTitle: 'Your presence, at specific moments', noticeIntro: 'Please read how checks work before enabling them.',
  noticeCollection: '2 or 3 times during your declared work day, a notification will ask for a site photo and your current GPS position, its accuracy, the time and the declared site. You have 30 minutes to respond.',
  noticePrivacy: 'No continuous tracking or background location access. The camera and GPS only activate after you tap. Avoid faces and personal information in the photo. No facial recognition.',
  noticeAccess: 'Proofs are available to you and your company’s chefs to check site presence. Photos and coordinates are retained for at most 30 days. Declared days and tasks remain in the company history.',
  noticeRights: 'Your company is responsible for this use. Contact your chef for its contact details, to exercise access, correction or objection rights, or to report a difficulty. You can withdraw agreement here to stop new requests.',
  noticeChoice: 'Declining or withdrawing does not prevent account access. A missed check is not proof of absence. Your employer must specify the applicable legal basis and requirements.',
  agreeLabel: 'I have read this information and agree to occasional checks with a photo and GPS.', accept: 'Enable checks', later: 'Later', withdraw: 'Withdraw agreement', withdrawConfirm: 'Withdrawing agreement will finish the current day and stop new requests.', info: 'Information and agreement',
  taskTitle: 'My tasks', taskHint: 'Choose a task and enter the total quantity completed today. Saving again replaces the previous quantity.',
  category: 'Trade', task: 'Task', chooseTask: 'Choose a task', quantity: 'Quantity completed', unit: 'unit(s)', metres: 'metres', taskSaved: 'Declaration saved', startForTasks: 'Start your day to declare tasks.',
  unitLong: { unit: 'unit(s)', m: 'metres', m2: 'square metres', m3: 'cubic metres', kg: 'kilograms' }, unitShort: { unit: 'u', m: 'm', m2: 'm²', m3: 'm³', kg: 'kg' },
  whole: 'Whole number', decimal: 'Decimals', useKeyboard: 'Type on keyboard', useWheel: 'Use the wheel',
  sitesTitle: 'Sites', sitesHint: 'Sites your team can declare.', addSite: 'Add a site', siteName: 'Site name', siteAddress: 'Address (optional)',
  history: 'Checks', historyHint: 'Occasional proofs with time and declared site. No live locations.', noChecks: 'No checks recorded yet.', viewProof: 'View proof', close: 'Close', accuracy: 'GPS accuracy',
  pushUnavailable: 'Notifications are unavailable on this device. Keep Today open and refresh to see requests.',
  nativeOnly: 'Use the mobile app to take an on-site photo and capture your position.',
  cameraDenied: 'Allow camera access to take a site photo.', locationDenied: 'Allow location access for this check.',
  failed: 'Unable to load data. Please retry.', invalidQuantity: 'Enter a valid positive quantity (a whole number for units).',
  proofFailed: 'The check was not saved. Take a new photo and retry within the response window.',
  inactive: 'This account is suspended. Contact your chef.',
};
export function workCopy(locale: Locale) { return locale === 'en' ? en : fr; }

/** Only whole units can be declared for countable tasks; every measured unit accepts decimals. */
export function isWholeUnit(unit: TaskUnit) { return unit === 'unit'; }
export function unitLong(unit: TaskUnit, copy: typeof fr) { return copy.unitLong[unit] ?? unit; }
export function unitShort(unit: TaskUnit, copy: typeof fr) { return copy.unitShort[unit] ?? unit; }
